version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  distobject-py:
    build:
      context: ./distobject-py-container
    volumes:
      - shared-data:/shared
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  test-runner:
    build:
      context: .
    volumes:
      - shared-data:/shared
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - distobject-py
    command: go test ./distobject/...

volumes:
  shared-data:
