version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    command: go test ./...
