package distobject

import (
	"os"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func TestPythonToGoToPython(t *testing.T) {
	// 1. Read key generated by Python
	keyBytes, err := os.ReadFile("/shared/key.txt")
	assert.NoError(t, err)

	id := strings.TrimSpace(string(keyBytes))
	assert.NotEmpty(t, id)

	// 2. Load object using Go and update
	r := NewRedisClient("redis:6379")
	user := &User{}
	d := NewDistObject(r, "user", "user-updates")

	time.Sleep(2 * time.Second) // Give Redis time to settle

	err = d.Load(id, user)
	assert.NoError(t, err)
	assert.Equal(t, "Alice", user.Name)

	user.Email = "updated-in-go@example.com"
	d.MarkChanged("email")
	err = d.Save(user)
	assert.NoError(t, err)

	// 3. Verify using direct Redis connection (Python will trust Go updated it)
	rdb := r.Client()
	data, err := rdb.HGetAll(ctx, id).Result()
	assert.NoError(t, err)
	assert.Equal(t, "updated-in-go@example.com", data["email"])
}
